const norwayTourData = [
    {
        id: 1,
        name: "Oslo",
        description: "The capital city of Norway, known for its modern architecture, cultural attractions, and green spaces.",
        attractions: ["Vigeland Park", "Royal Palace", "Munch Museum"],
        price: "$$",
        rating: 4.5,
        imageUrl: "https://plus.unsplash.com/premium_photo-1661963273758-b26e0477d1c2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bm9yd2F5JTIwdG91cmlzbXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id: 2,
        name: "Bergen",
        description: "A charming coastal city surrounded by fjords and mountains, famous for its colorful wooden houses.",
        attractions: ["Bryggen Wharf", "Fløyen Mountain", "Fish Market"],
        price: "$$",
        rating: 4.7,
        imageUrl: "https://images.unsplash.com/photo-1618219637950-8563dd97dc54?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bm9yd2F5JTIwdG91cmlzbXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id: 3,
        name: "Tromsø",
        description: "Located in the Arctic Circle, Tromsø offers stunning Northern Lights views and Arctic adventures.",
        attractions: ["Arctic Cathedral", "Polaria Museum", "Fjellheisen Cable Car"],
        price: "$$$",
        rating: 4.2,
        imageUrl: "https://images.unsplash.com/photo-1526080676457-4544bf0ebba9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDR8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=400&q=60",
    },
    {
        id: 4,
        name: "Trondheim",
        description: "A historic city with a medieval cathedral and vibrant student culture.",
        attractions: ["Nidaros Cathedral", "Old Town Bridge", "Rockheim Museum"],
        price: "$$",
        rating: 4.0,
        imageUrl: "https://images.unsplash.com/photo-1564086315895-f3f695934f3a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=300&q=60",
    },
    {
        id: 5,
        name: "Geirangerfjord",
        description: "A UNESCO World Heritage Site known for its breathtaking fjord landscapes.",
        attractions: ["The Seven Sisters Waterfall", "Dalsnibba Viewpoint", "Fjord Cruises"],
        price: "$$$",
        rating: 4.8,
        imageUrl: "https://images.unsplash.com/photo-1571989237340-98fb838eeef1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHx8&auto=format&fit=crop&w=300&q=60",
    },
    {
        id: 6,
        name: "Lofoten Islands",
        description: "A group of stunning islands known for fishing villages, dramatic landscapes, and outdoor activities.",
        attractions: ["Reine Village", "Hiking Trails", "Kayaking"],
        price: "$$$",
        rating: 4.6,
        imageUrl: "https://images.unsplash.com/photo-1600255941108-a9ac5d0237f2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE5fHx8ZW58MHx8fHx8&auto=format&fit=crop&w=300&q=60",
    },
    {
        id: 7,
        name: "Stavanger",
        description: "A coastal city known for its oil industry, picturesque old town, and nearby natural attractions.",
        attractions: ["Preikestolen", "Stavanger Cathedral", "Norwegian Petroleum Museum"],
        price: "$$",
        rating: 4.3,
        imageUrl: "https://images.unsplash.com/photo-1600449849530-d112940aeaa0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDd8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=400&q=60",
    },
    {
        id: 8,
        name: "Alesund",
        description: "Famed for its art nouveau architecture and stunning views of the surrounding islands.",
        attractions: ["Alesund Aquarium", "Aksla Viewpoint", "Art Nouveau Center"],
        price: "$$",
        rating: 4.4,
        imageUrl: "https://plus.unsplash.com/premium_photo-1690323262455-13ce6c0e2166?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE2fHx8ZW58MHx8fHx8&auto=format&fit=crop&w=400&q=60",
    },
    {
        id: 9,
        name: "Haugesund",
        description: "A coastal town known for its history, film festival, and access to outdoor adventures.",
        attractions: ["Haraldshaugen Monument", "Avaldsnes Historic Centre", "Karmøy Beaches"],
        price: "$$",
        rating: 4.1,
        imageUrl: "https://images.unsplash.com/photo-1609562044137-0a9d512c73e8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE5fHx8ZW58MHx8fHx8&auto=format&fit=crop&w=400&q=60",
    },
    {
        id: 10,
        name: "Molde",
        description: "Famous for its annual jazz festival and its stunning location by the Romsdal Fjord.",
        attractions: ["Molde International Jazz Festival", "Molde Cathedral", "Romsdal Museum"],
        price: "$$",
        rating: 4.2,
        imageUrl: "https://plus.unsplash.com/premium_photo-1661963290283-a1883fb9582a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8bm9yd2F5JTIwdG91cmlzbXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=700&q=60",
    },
    {
        id: 11,
        name: "Svalbard",
        description: "An Arctic archipelago known for its polar bears, glaciers, and unique wildlife experiences.",
        attractions: ["Polar Bear Spotting", "Arctic Wilderness Tours", "Svalbard Global Seed Vault"],
        price: "$$$",
        rating: 4.9,
        imageUrl: "https://plus.unsplash.com/premium_photo-1661962266500-5660d27eb5f9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDh8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=300&q=60",
    },
    {
        id: 12,
        name: "Ålesund",
        description: "A picturesque town known for its art nouveau architecture and access to outdoor activities.",
        attractions: ["Art Nouveau Centre", "Aksla Viewpoint", "Ålesund Aquarium"],
        price: "$$",
        rating: 4.4,
        imageUrl: "https://images.unsplash.com/photo-1581975333092-af8f70c1ca73?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDExfHx8ZW58MHx8fHx8&auto=format&fit=crop&w=300&q=60",
    },
    {
        id: 13,
        name: "Narvik",
        description: "A town in northern Norway known for its stunning fjord and mountain scenery.",
        attractions: ["Narvik War Museum", "Narvikfjellet Ski Resort", "Ofoten Railway"],
        price: "$$",
        rating: 4.3,
        imageUrl: "https://images.unsplash.com/photo-1593291805141-990f40ec982d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE1fHx8ZW58MHx8fHx8&auto=format&fit=crop&w=300&q=60",
    },
    {
        id: 14,
        name: "Kristiansand",
        description: "A vibrant coastal city known for its zoo, beaches, and family-friendly attractions.",
        attractions: ["Kristiansand Zoo and Amusement Park", "Bystranda Beach", "Ravnedalen Park"],
        price: "$$",
        rating: 4.0,
        imageUrl: "https://images.unsplash.com/photo-1554140781-de7d3bd7d75e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE5fHx8ZW58MHx8fHx8&auto=format&fit=crop&w=300&q=60",
    },
    {
        id: 15,
        name: "Hammerfest",
        description: "The northernmost town in the world, offering a unique Arctic experience.",
        attractions: ["Royal and Ancient Polar Bear Society", "Meridian Column", "Museum of Post-war Reconstruction"],
        price: "$$",
        rating: 4.1,
        imageUrl: "https://images.unsplash.com/photo-1600255941108-a9ac5d0237f2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8bm9yd2F5JTIwdG91cmlzbXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=700&q=60",
    },
    {
        id: 16,
        name: "Mandal",
        description: "A coastal town known for its sandy beaches, cultural attractions, and outdoor activities.",
        attractions: ["Sjøsanden Beach", "Mandal Museum", "Skjernøy Island"],
        price: "$$",
        rating: 4.2,
        imageUrl: "https://images.unsplash.com/photo-1516865861419-3e010572b6df?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fG5vcndheSUyMHRvdXJpc218ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=700&q=60",
    },
    {
        id: 17,
        name: "Nordkapp",
        description: "A famous cliff and popular tourist destination, often referred to as the northernmost point of Europe.",
        attractions: ["Nordkapp Plateau", "Nordkapphallen Visitor Centre", "Midnight Sun Experience"],
        price: "$$$",
        rating: 4.6,
        imageUrl: "https://images.unsplash.com/photo-1600255941053-6e3b95f1da83?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fG5vcndheSUyMHRvdXJpc218ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=700&q=60",
    },
    {
        id: 18,
        name: "Ålesund",
        description: "A picturesque town known for its art nouveau architecture and access to outdoor activities.",
        attractions: ["Art Nouveau Centre", "Aksla Viewpoint", "Ålesund Aquarium"],
        price: "$$",
        rating: 4.4,
        imageUrl: "https://images.unsplash.com/photo-1581975333092-af8f70c1ca73?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDExfHx8ZW58MHx8fHx8&auto=format&fit=crop&w=300&q=60",
    },
    {
        id: 19,
        name: "Svalbard",
        description: "An Arctic archipelago known for its polar bears, glaciers, and unique wildlife experiences.",
        attractions: ["Polar Bear Spotting", "Arctic Wilderness Tours", "Svalbard Global Seed Vault"],
        price: "$$$",
        rating: 4.9,
        imageUrl: "https://plus.unsplash.com/premium_photo-1661962266500-5660d27eb5f9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDh8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=300&q=60",
    },
    {
        id: 4,
        name: "Trondheim",
        description: "A historic city with a medieval cathedral and vibrant student culture.",
        attractions: ["Nidaros Cathedral", "Old Town Bridge", "Rockheim Museum"],
        price: "$$",
        rating: 4.0,
        imageUrl: "https://images.unsplash.com/photo-1564086315895-f3f695934f3a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=300&q=60",
    },
    
];

export default norwayTourData;
